# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.16-node
    working_directory: /go/src/github.com/blindsidenetworks/mattermost-plugin-bigbluebutton
    steps:
      - checkout
      - run: make check-style
      - run: make dist
      - store_artifacts:
          path: ./dist
          destination: build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  release:
    docker:
      - image: circleci/golang:1.16-node
    working_directory: /go/src/github.com/blindsidenetworks/mattermost-plugin-bigbluebutton
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: make release

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
  build-and-release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
